[[MParT]]
arch = "aarch64"
git-tree-sha1 = "d3c95369fcf41a6302bec8d693cf3079dab4340a"
os = "macos"

    [[MParT.download]]
    sha256 = "e0cdfc5862a67dd22424d8885e74fdec665bc7cb90e87073489228cfedcb1283"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.aarch64-apple-darwin.tar.gz"
[[MParT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec5b22b1c7605b09edc97391cff0db0a06b1dded"
libc = "glibc"
os = "linux"

    [[MParT.download]]
    sha256 = "f0cfe53712c1f43f9f40ba71315d68a4cabfae79b71be5a56935424249845326"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MParT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1b58184e35fb5a7ddf3a8bfe7412301c6b9ba93"
libc = "glibc"
os = "linux"

    [[MParT.download]]
    sha256 = "f370383ad87fd6990c9b06512c26e8ec05ad6172bb3a53a72f7b3623d26168d4"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MParT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef28060f4b1ef0b98a079c38058d356a80c1465c"
libc = "musl"
os = "linux"

    [[MParT.download]]
    sha256 = "6ae104b163c3cebade992720f0ea905b9977d65d4f5b06e38762cbf433907583"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[MParT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae8fb4e92f209bb07460a20ef50847993707a248"
libc = "musl"
os = "linux"

    [[MParT.download]]
    sha256 = "72d891dd672488f9c3b9f0ee6859deeb49edb9a18f945f238eb2d5688d8c138f"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[MParT]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c467269a4a41828dfa233d86ada5b5df073ec1a3"
libc = "glibc"
os = "linux"

    [[MParT.download]]
    sha256 = "fe1cf7715e97483e18acb16c369c9f7227d4cd98f67d027be250d7d9d36a3ae5"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MParT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4366347df0027fcbf74aa2131e588e4d0077aeca"
libc = "glibc"
os = "linux"

    [[MParT.download]]
    sha256 = "a2b750a2f81dbdeac3c5d4bc33da13926f5cf4a813f86f3d98e0fff2347d065b"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MParT]]
arch = "x86_64"
git-tree-sha1 = "d5fef8e6170807c0aa279bf7913a6ba5bbc317bd"
os = "macos"

    [[MParT.download]]
    sha256 = "02241b2b67dc2d6ada8aae053f84fed4278fe982c219dfd07081d4302204c55b"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.x86_64-apple-darwin.tar.gz"
[[MParT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bb43a43cff4eebbe70aef688ea2c0f9dca0905c"
libc = "glibc"
os = "linux"

    [[MParT.download]]
    sha256 = "608c216f080936eaaa3e96f1fad697ede9e2b3cfcd8dc79ba95c03061753710e"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MParT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe4d3409151d9bad48df956d8852b32178a34947"
libc = "glibc"
os = "linux"

    [[MParT.download]]
    sha256 = "20b093dd574bc571effec15706e7414964f3b7e3da2237c2c49608415a93b7cd"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MParT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a801093e4719f510663fc52f48e1aad145fa02c"
libc = "musl"
os = "linux"

    [[MParT.download]]
    sha256 = "5b6fcbad44e198de7d91cdf7988f389264d53e99e4a37daf7eee05182acd0d25"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[MParT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1330a220b3d7ff8850be71245705cdd784cfbfd4"
libc = "musl"
os = "linux"

    [[MParT.download]]
    sha256 = "b922f95694ec5ecf42cccc14c54ea23d40e5a9e1b159fd3f356b71f8276be5cc"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[MParT]]
arch = "x86_64"
git-tree-sha1 = "4298c826dde9f7f1feb1e71c345e407566de6f9c"
os = "freebsd"

    [[MParT.download]]
    sha256 = "cfebc5605fdd3756b903678a4a282dd429e1f1a597a260e331422a0946fb6e6a"
    url = "https://github.com/JuliaBinaryWrappers/MParT_jll.jl/releases/download/MParT-v0.2.0+0/MParT.v0.2.0.x86_64-unknown-freebsd.tar.gz"
